VariantViewer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import include
from django.urls import path

from . import views

urlpatterns = [
    path('api/', include('web.routing')),

    path('', views.RedirectView.as_view(), kwargs={
         'update': False}, name='redirect'),
    path('section-update', views.RedirectView.as_view(),
         kwargs={'update': True}, name='change_section'),

    path('<slug:section>', views.HomeView.as_view(), name='home'),

    path('<slug:section>/search', views.SearchView.as_view(), name='search'),

    path('results/<pipeline_version>/<worksheet>/<sample>',
         views.SampleDetailsView.as_view(), name='sample_details'),


    ######################
    ##### AJAX VIEWS #####
    ######################

    path('ajax/run_first_check/<int:pk>',
         views.run_first_check, name='run_first_check'),

    path('ajax/run_second_check/<int:pk>',
         views.run_second_check, name='run_second_check'),

    path('ajax/modify_filters/<int:run>/<int:ss_sample>/<filter>',
         views.modify_filters, name='modify_filters'),

    path('ajax/update_selected_transcript/<int:run>/<int:ss_sample>/<int:transcript>',
         views.update_selected_transcript, name='update_selected_transcript'),

    path('ajax/load_variant_list/<int:run>/<int:ss_sample>',
         views.load_variant_list, name='load_variant_list'),

    path('ajax/refresh_classification_indicators/<int:run>', views.refresh_classification_indicators,
         name='refresh_classification_indicators'),

    path('ajax/load_variant_details/<int:run>/<int:stv>',
         views.load_variant_details, name='load_variant_details'),

    path('ajax/pin_variant/<int:run>/<int:stv>',
         views.pin_variant, name='pin_variant'),

    path('ajax/comment_update_or_create/<int:run>/<int:stv>',
         views.comment_update_or_create, name='comment_update_or_create'),

    path('ajax/save_evidence/<int:stv>',
         views.save_evidence, name='save_evidence'),

    path('ajax/archive_evidence/<int:document>',
         views.archive_evidence, name='archive_evidence'),

    path('ajax/load_previous_evidence/<int:run>/<int:current_stv>/<int:previous_stv>',
         views.load_previous_evidence, name='load_previous_evidence'),

    path('ajax/report_update_or_create/<int:run>/<int:ss_sample>/<report>',
         views.report_update_or_create, name='report_update_or_create'),

    path('ajax/generate_report/', views.GenerateReport,
         name='generate_report'),

    path('ajax/generate_variant_diagram/', views.GenerateVariantDiagram,
         name='generate_variant_diagram'),

    # Temporary to explore jbrowse during development
    path('jbrowse-testing/', views.JbrowseTestingView.as_view(),
         name='jbrowse-testing')

]

db/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_save
from django.template.defaultfilters import slugify
from django.core.exceptions import ValidationError

from db.utils.model_utils import BaseModel
from db.utils.model_utils import PipelineOutputFileModel
from db.utils.model_utils import mode


class Section(BaseModel):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, unique=True, null=True)

    def __str__(self):
        return self.name


@receiver(pre_save, sender=Section)
def set_section_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)


class Pipeline(BaseModel):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class PipelineSection(BaseModel):
    section = models.ForeignKey(
        Section,
        on_delete=models.CASCADE
    )
    pipeline = models.ForeignKey(
        Pipeline,
        on_delete=models.CASCADE
    )
    default = models.BooleanField(default=False)


class Samplesheet(BaseModel):
    path = models.CharField(max_length=255, unique=True)

    latest_run = models.ForeignKey(
        'Run',
        blank=True,
        null=True,
        on_delete=models.PROTECT,
        related_name='latest')

    def __str__(self):
        return self.path


class PipelineVersion(BaseModel):
    version = models.CharField(max_length=255)
    pipeline = models.ForeignKey(
        Pipeline,
        on_delete=models.CASCADE
    )
    updates = models.OneToOneField(
        "PipelineVersion",
        null=True,
        on_delete=models.SET_NULL,
        related_name='updated_by'
    )

    default_filter = models.ForeignKey(
        'web.Filter',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def default_classification_options():
        return [{'classification': 'Unclassified', 'colour': 'blue'},
                {'classification': 'Benign', 'colour': 'green'},
                {'classification': 'Likely Benign', 'colour': 'olive'},
                {'classification': 'VUS', 'colour': 'yellow'},
                {'classification': 'Likely Pathogenic', 'colour': 'orange'},
                {'classification': 'Pathogenic', 'colour': 'red'}]

    classification_options = models.JSONField(
        default=default_classification_options)

    def __str__(self):
        return f"{self.pipeline} {self.version}"

    def clean(self):
        stvs = SampleTranscriptVariant.objects.filter(sample_variant__sample__samplesheets__runs__pipeline_version=self).exclude(
            comment__classification__isnull=True).exclude(comment__classification=0)

        if stvs:
            raise ValidationError(
                "Variants have already been classified using this pipeline version, it cannot be modified. "
                "Please create a new pipeline version to make any changes.")

    class Meta:
        unique_together = ['version', 'pipeline']


class Run(BaseModel):
    # Choice field for run QC status
    class Status(models.IntegerChoices):
        PENDING = 0
        PASS = 1
        FAIL = 2

    worksheet = models.CharField(max_length=255)
    command_line_usage = models.TextField()
    completed_at = models.DateTimeField()
    samplesheet = models.ForeignKey(
        Samplesheet,
        on_delete=models.PROTECT,
        related_name='runs'
    )
    config_file = models.CharField(max_length=255)
    output_dir = models.CharField(max_length=255)
    fastq_dir = models.CharField(max_length=255)
    interop_dir = models.CharField(max_length=255)
    pipeline_version = models.ForeignKey(
        PipelineVersion,
        on_delete=models.PROTECT,
        related_name='pipeline_version'
    )
    qc_status = models.IntegerField(
        choices=Status.choices,
        default=0,
    )

    # whether run qc_status has been checked by a second user.
    checked = models.BooleanField(default=False)

    # Method to retrieve all samples associated with a run
    def get_samples(self):
        return SamplesheetSample.objects.filter(samplesheet__runs__id=self.id)

    def __str__(self):
        return f"{self.worksheet}"


# noinspection PyUnusedLocal
@receiver(post_save, sender=Run)
def set_latest_run(sender, instance, *args, **kwargs):
    # Ensure latest run is always set to the most recently completed run associated with a given samplesheet.
    instance.samplesheet.latest_run = Run.objects.filter(
        samplesheet=instance.samplesheet).order_by('-completed_at')[0]
    instance.samplesheet.save()


# noinspection PyAbstractClass
class BAM(PipelineOutputFileModel):
    pass


# noinspection PyAbstractClass
class VCF(PipelineOutputFileModel):
    filters = models.ManyToManyField(
        'web.Filter',
        through="VCFFilter"
    )


class VCFFilter(BaseModel):
    """
    Representation of filter associated with a particular VCF file.
    """
    vcf = models.ForeignKey(
        VCF,
        on_delete=models.CASCADE
    )
    filter = models.ForeignKey(
        'web.Filter',
        on_delete=models.CASCADE
    )


class GenomeBuild(BaseModel):
    name = models.CharField(max_length=255)
    path = models.TextField(unique=True, null=True)
    url = models.URLField(null=True)

    def __str__(self):
        return self.name


class Patient(BaseModel):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class Sample(BaseModel):
    lab_no = models.CharField(max_length=50, unique=True)
    section = models.ForeignKey(
        Section,
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name='samples'
    )
    patient = models.ForeignKey(
        Patient,
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name='samples'
    )
    samplesheets = models.ManyToManyField(
        Samplesheet,
        through="SamplesheetSample"
    )
    bams = models.ManyToManyField(
        BAM,
        through="SampleBAM"
    )
    vcfs = models.ManyToManyField(
        VCF,
        through="SampleVCF"
    )

    @classmethod
    def SetSampleSection(self, sample):
        # Retrieve the set of pipelines associated with any of the sample's runs across any samplesheet the sample appears in.
        sample_pipelines = [run.pipeline_version.pipeline for samplesheet in sample.samplesheets.all(
        ) for run in samplesheet.runs.all()]

        # Retrieve the sections that have been associated with these pipelines.
        valid_pipeline_sections = PipelineSection.objects.filter(
            pipeline__in=sample_pipelines)

        if sample_pipelines and sample.section not in [pipeline_section.section for pipeline_section in valid_pipeline_sections]:
            try:
                # If only one pipeline associated with sample, find default section associated with it.
                if len(sample_pipelines) == 1:
                    default = valid_pipeline_sections.get(default=True).section
                # If multiple pipelines associated with sample, use custom mode function to
                # check if there is a mode and if so return default section associated with it.
                elif mode(sample_pipelines):
                    default = valid_pipeline_sections.get(
                        pipeline=mode(sample_pipelines), default=True).section
                # If multiple pipelines associated with sample, but no mode (e.g. each pipeline has been associated to sample an
                # equal number of times), return default section associated with the pipeline of the most recent run.
                else:
                    latest_pipeline = Run.objects.filter(
                        samplesheet__in=sample.samplesheets.all()).order_by('-completed_at')[0].pipeline_version.pipeline
                    default = valid_pipeline_sections.get(
                        pipeline=latest_pipeline, default=True).section
                sample.section = default
                sample.save()
            except PipelineSection.DoesNotExist:
                # If no default section for sample's pipeline, leave it blank.
                pass

    def __str__(self):
        return self.lab_no

    class Meta:
        indexes = [
            models.Index(fields=['lab_no'])
        ]


@receiver(post_save, sender=Sample)
def set_sample_section(sender, instance, *args, **kwargs):
    Sample.SetSampleSection(instance)


# noinspection PyAbstractClass
class ExcelReport(PipelineOutputFileModel):
    """Excel report for a patient, can relate directly to sample."""
    sample = models.ForeignKey(
        Sample,
        on_delete=models.CASCADE
    )


class SamplesheetSample(BaseModel):
    samplesheet = models.ForeignKey(
        Samplesheet,
        on_delete=models.PROTECT,
        related_name='samplesheet'
    )
    sample = models.ForeignKey(
        Sample,
        on_delete=models.PROTECT,
        related_name='sample'
    )
    sample_identifier = models.CharField(max_length=50)
    index = models.CharField(max_length=50)
    index2 = models.CharField(max_length=50, null=True, blank=True)
    gene_key = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.samplesheet} {self.sample_identifier}"


class SampleBAM(BaseModel):
    """
    Representation of info of a particular sample being present in a BAM file
    """
    sample = models.ForeignKey(
        Sample,
        on_delete=models.CASCADE
    )
    bam = models.ForeignKey(
        BAM,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f"{self.sample.lab_no} BAM: {self.bam.path.split('/')[-1]}"


class SampleVCF(BaseModel):
    """
    Representation of info of a particular sample being present in a VCF file

web/templates/includes/active-filters.html
<div class="subtitle">FILTERS:</div>
{% if filters.active_filter %}

{% if filters.active_filter == filters.blank_filter %}

<a class="ui red right  icon tag label selectable" id="mod_filter" data-position="bottom center"
    data-html="<span>Add filters</span>"
    data-url="{% url 'modify_filters' ss_sample=ss_sample.id run=run.id filter=filters.active_filter.id %}">
    ALL FILTERS DISABLED
    <i class="sliders horizontal icon"></i>
</a>

{% else %}

<!-- Scrollable filters display -->
<a id="left-button" class="ui circular icon label" style="margin-right: 5px;">
    <i class="arrow alternate left icon"></i>
</a>

<div id='left-ellipses' style='display: inline-flex;align-items: center;position: relative;pointer-events: none;'>
    <div
        style="position: absolute;left: 2px;width: 60px;background-color: #5c5c5cde;text-align: center;color: white;border-radius: 5px;border: 1px white solid;">
        <span style="font-size: smaller; font-weight: bold;">{{filters.active_filter.items.count}} items</span>
    </div>
</div>



<!-- Make sure content has flex-shrink:0 -->
<div class="active-filters-container">
    {% for item in filters.active_filter.items.all %}

    <div class="ui label item" data-or-next="{{item.or_next}}" style="flex-shrink: 0;">
        {{item.field}}
        <div class="detail">{{item.get_filter_type_display}}</div>
        <div class="detail">{{item.value}}</div>
    </div>

    {% if not forloop.last %}
    <div class="ui grey circular label" style="margin-left: 3px;margin-right: 3px;">
        {% if item.or_next %}
        or
        {% else %}
        &
        {%endif%}
    </div>
    {%endif%}

    {% endfor %}

    <div class="hidden grouper-before">
        <span class="ui grey text" style="font-size: 38px;margin-top: -4px;margin-right: -3px;">
            [
        </span>
    </div>
    <div class="hidden grouper-after">
        <span class="ui grey text" style="font-size: 38px;margin-top: -4px;margin-left: -3px;">
            ]
        </span>
    </div>
</div>

<div id='right-ellipses' style='display: inline-flex;align-items: center;position: relative;pointer-events: none;'>
    <div
        style="position: absolute;right: 2px;width: 60px;background-color: #5c5c5cde;text-align: center;color: white;border-radius: 5px;border: 1px white solid;">
        <span style="font-size: smaller; font-weight: bold;">{{filters.active_filter.items.count}} items</span>
    </div>
</div>

<a id="right-button" class="ui circular icon label" style="margin-left:5px;margin-right: 15px;">
    <i class="arrow alternate right icon"></i>
</a>

{% if filters.active_filter == filters.pipeline_default_filter %}
<a class="ui grey right icon tag label selectable" data-position="bottom center" data-html="<span>Modify filters</span>"
    id="mod_filter"
    data-url="{% url 'modify_filters' ss_sample=ss_sample.id run=run.id filter=filters.active_filter.id %}">
    DEFAULT PRESET:
    <div class="detail">'{{filters.active_filter.name}}'</div>
    <i class="sliders horizontal icon"></i>
</a>

{% else %}
<a class="ui orange right icon tag label selectable" data-position="bottom center"
    data-html="<span>Modify filters</span>" id="mod_filter"
    data-url="{% url 'modify_filters' ss_sample=ss_sample.id run=run.id filter=filters.active_filter.id %}">
    USER PRESET:
    <div class="detail">'{{filters.active_filter.name}}'</div>
    <i class="sliders horizontal icon"></i>
</a>
{% endif %}

{%endif%}

{%else%}

<a class="ui grey right  icon tag label selectable" id="mod_filter" data-position="bottom center"
    data-html="<span>Add filters</span>"
    data-url="{% url 'modify_filters' ss_sample=ss_sample.id run=run.id filter='None' %}">
    ADD FILTERS
    <i class="sliders horizontal icon"></i>
</a>

{%endif%}

web/templates/includes/archive-evidence.html
<div class="ui segments" style="display: flex;min-width: 40%;max-width: 90%;max-height: 90%;">
    <div class="ui left aligned clearing segment">
        <h3 class="ui header" style="margin:0">Archive '{{document.filename }}'</h3>
    </div>
    <div class="ui left aligned segment" style="flex: 1;overflow: auto;">
        <form id='archive-evidence-form' method="post" action="{% url 'archive_evidence' document=document.id %}"
            class="js-archive-evidence-form">

            {% csrf_token %}

        </form>
        <span>Are you sure you want to archive this evidence file?</span>


    </div>
    <div class="ui secondary left aligned clearing segment">
        <input type="submit" value="Archive" form="archive-evidence-form" class="ui right floated negative button"
            style="margin-left: 10px;">
        <div class="ui right floated button archive-evidence-close">Cancel</div>
    </div>
</div>

web/templates/includes/run-first-check.html
<style>
    .set-status-modal {
        display: flex;
        width: 33cm;
        height: 20cm;
        margin: 0 !important;
    }

    @media (max-width: 45cm) {
        .set-status-modal {
            width: 80%
        }
    }

    @media (max-height: 30cm) {
        .set-status-modal {
            height: 80%
        }
    }
</style>


<div class="ui segments set-status-modal">
    <div class="ui left aligned clearing segment">
        <h3 class="ui header" style="margin:0">Run QC Check: {{run.worksheet}} </h3>
    </div>
    <div class="ui left aligned segment" style="display: flex;flex: 1;overflow: auto;padding: 0;">

        <div class="status-options">
            <div class="pass option" data-value="pass">
                Pass
            </div>

            <div style="background-color: #D5D5D6;height: 1px;"></div>
            <div class="fail option" data-value="fail">
                Fail
            </div>
        </div>

        <div style="flex: 1;padding: 0px;">
            <!-- <div class="ui segment" style="align-self: stretch;">qc stuff!</div>

            {% for sample in run.samplesheet.sample_set.all %}
            <div class="ui raised segment">{{sample}}</div>
            {% endfor %} -->

            <iframe src="https://multiqc.info/examples/wgs/multiqc_report.html" width="100%" height="100%"
                style="border: 0;">
                <p>Your browser does not support iframes.</p>
            </iframe>
        </div>




        <form id='worksheet-detail-form' method="post" action="{% url 'run_first_check' pk=run.id %}"
            class="js-worksheet-detail-form">

            {% csrf_token %}

            <input type="hidden" id="qc_status_input" name="qc_status" value="">

        </form>
        <!-- <span class='ui grey small text' style="text-align: left"> Last modified by </span> -->


    </div>
    <div class="ui secondary left aligned clearing segment">
        <div style="margin-left: 10px;" class="ui right floated primary disabled button worksheet-detail-save">Save
        </div>
        <div class="ui right floated button worksheet-detail-close">Cancel</div>
    </div>
</div>



<div class="ui segments confirm-status-modal" style="display: flex;min-width: 40%;max-width: 90%;max-height: 90%;">
    <div class="ui left aligned clearing segment">
        <h3 class="ui header" style="margin:0" data-worksheet="{{run.worksheet|upper }}"></h3>
    </div>
    <div class="ui left aligned segment" style="flex: 1;overflow: auto;">
        <span class="body-text"></span>
    </div>
    <div class="ui secondary left aligned clearing segment">
        <input type="submit" value="Confirm" form="worksheet-detail-form" class="ui right floated negative button"
            style="margin-left: 10px;">
        <div class="ui right floated button cancel-submit">Cancel</div>
    </div>
</div>

<style>
    .check-option {
        display: flex;
        flex: 0 0 5%;
        align-items: center;
        justify-content: center;
        background-color: grey;
    }

    .status-options {
        display: flex;
        flex: 0 0 10%;
        flex-direction: column;
        border-left: rgba(34, 36, 38, 0.15);
        border-right: 2.25px solid #D5D5D6;

    }

    .option {
        display: flex;
        flex: 1;
        opacity: 0.6;
        align-items: center;
        justify-content: center;
        background-color: rgb(211, 211, 212);
        cursor: pointer;
        font-weight: 700;
        transition: background-color 100ms linear;
        transition: opacity 100ms ease-in;

    }

    .option:not(.selected):hover {
        opacity: 1;
        background-color: rgb(202, 203, 205);
    }

    .option:not(.selected):active {
        opacity: 1;
        box-shadow: inset 0px 0px 10px #88888867 !important;
    }

    .pass {
        color: rgba(0, 128, 0, 0.7);
    }

    .fail {
        color: rgba(255, 0, 0, 0.7);
    }

    .pass.option.selected {
        background-color: rgba(66, 160, 66, 0.15);
        transition: background-color 200ms linear;
    }

    .fail.option.selected {
        background-color: rgb(212, 0, 0, 0.15);
        transition: background-color 200ms linear;

    }

    .option.selected {
        cursor: default;
        -webkit-box-shadow: inset 0px 0px 5px #33333352 !important;
        -moz-box-shadow: inset 0px 0px 5px #33333352 !important;
        box-shadow: inset 0px 0px 5px #33333352 !important;
        opacity: 1;
        /* color: rgba(255, 255, 255, 0.9); */
        /* border: 1px solid #555; */
    }
</style>

<script>
    $('.confirm-status-modal').hide()

    $('.option').click(function () {
        $('.option').removeClass('selected')
        $(this).addClass('selected')
        $('.worksheet-detail-save').removeClass('disabled')

        $('#qc_status_input').val($(this).attr('data-value'))

        header = $(this).text() + ' ' + $('.confirm-status-modal .header').attr('data-worksheet') + ' QC'
        body_text = 'Are you sure you want to ' + $(this).attr('data-value') + ' this run?'
        $('.confirm-status-modal .header').text(header)
        $('.confirm-status-modal .body-text').text(body_text)
    })

    $('.cancel-submit').click(function () {
        $('.confirm-status-modal').fadeOut(function () {
            $('.set-status-modal').fadeIn();
        })
    })

    $('.worksheet-detail-save').click(function () {
        $('.set-status-modal').fadeOut(function () {
            $('.confirm-status-modal').fadeIn();
        })
    })

</script>

web/templates/includes/run-second-check.html
{% load humanize %}

<style>
    .set-status-modal {
        display: flex;
        width: 33cm;
        height: 20cm;
        margin: 0 !important;
    }

    @media (max-width: 45cm) {
        .set-status-modal {
            width: 80%
        }
    }

    @media (max-height: 30cm) {
        .set-status-modal {
            height: 80%
        }
    }
</style>

<div class="ui segments set-status-modal">
    <div class="ui left aligned clearing segment">
        <h3 class="ui header" style="margin:0">Run QC Second Check: {{run.worksheet}} </h3>
    </div>
    <div class="ui left aligned segment" style="display: flex;flex: 1;overflow: hidden;padding: 0;">

        <div class="status-options">

            {% if run.qc_status == 1 %}
            <div class="pass option selected" data-value="pass">
                Pass
            </div>
            {% else %}
            <div class="fail option selected" data-value="fail">
                Fail
            </div>
            {% endif%}
        </div>

        <div style="display: flex; flex-direction: column; flex: 1;">
            <div class="ui attached segment" style="border-top: none;">
                <div class="ui message">

                    {% if user == last_updated.fields.qc_status.user %}
                    First QC check conducted by you
                    {{last_updated.fields.qc_status.datetime|naturaltime}}. The
                    {% if run.qc_status == 1 %}pass{% else %}fail{% endif%} result must be confirmed or rejected by
                    another user.
                    {% else %}
                    First QC check conducted by {{last_updated.fields.qc_status.user.get_full_name}}
                    {{last_updated.fields.qc_status.datetime|naturaltime}}. Please
                    confirm or reject the
                    {% if run.qc_status == 1 %}pass{% else %}fail{% endif%} result.
                    {% endif %}


                </div>
            </div>

            <div class="ui attached segment" style="flex: 1;border-bottom: none;padding: 0;">
                <!-- {% for sample in run.samplesheet.sample_set.all %}
                <div class="ui raised segment">{{sample}}</div>
                {% endfor %} -->

                <iframe src="https://multiqc.info/examples/wgs/multiqc_report.html" width="100%" height="100%"
                    style="border: 0;">
                    <p>Your browser does not support iframes.</p>
                </iframe>
            </div>


        </div>




        <form id='worksheet-detail-form' method="post" action="{% url 'run_second_check' pk=run.id %}"
            class="js-worksheet-detail-form">

            {% csrf_token %}

            <input type="hidden" id="qc_status_second_check_input" name="qc_status_second_check" value="">

        </form>
        <!-- <span class='ui grey small text' style="text-align: left"> Last modified by </span> -->


    </div>
    <div class="ui secondary left aligned clearing segment">
        <div style="margin-left: 10px;"
            class="ui right floated positive button second-check-save {% if user == last_updated.fields.qc_status.user %}disabled{%endif%}"
            data-value="accept">
            Accept
        </div>
        <div style="margin-left: 10px;"
            class="ui right floated negative button second-check-save {% if user == last_updated.fields.qc_status.user %}disabled{%endif%}"
            data-value="reject">
            Reject
        </div>
        <div class="ui right floated button worksheet-detail-close">Cancel</div>
    </div>
</div>

<div class="ui segments confirm-status-modal" style="display: flex;min-width: 40%;max-width: 90%;max-height: 90%;">
    <div class="ui left aligned clearing segment">
        <h3 class="ui header" style="margin:0" data-worksheet="{{run.worksheet|upper }}"></h3>
    </div>
    <div class="ui left aligned segment" style="flex: 1;overflow: auto;">
        <span class="body-text"></span>
    </div>
    <div class="ui secondary left aligned clearing segment">
        <input type="submit" value="Confirm" form="worksheet-detail-form" class="ui right floated negative button"
            style="margin-left: 10px;">
        <div class="ui right floated button cancel-submit">Cancel</div>
    </div>
</div>

<style>
    .check-option {
        display: flex;
        flex: 0 0 5%;
        align-items: center;
        justify-content: center;
        background-color: grey;
    }

    .status-options {
        display: flex;
        flex: 0 0 10%;
        flex-direction: column;
        border-left: rgba(34, 36, 38, 0.15);
        border-right: 2.25px solid #D5D5D6;

    }

    .option {
        display: flex;
        flex: 1;
        opacity: 0.6;
        align-items: center;
        justify-content: center;
        background-color: rgb(211, 211, 212);
        cursor: pointer;
        font-weight: 700;
        transition: background-color 100ms linear;
        transition: opacity 100ms ease-in;

    }

    .option:not(.selected):hover {
        opacity: 1;
        background-color: rgb(202, 203, 205);
    }

    .option:not(.selected):active {
        opacity: 1;
        box-shadow: inset 0px 0px 10px #88888867 !important;
    }

    .pass {
        color: rgba(0, 128, 0, 0.7);
    }

    .fail {
        color: rgba(255, 0, 0, 0.7);
    }

    .pass.option.selected {
        background-color: rgba(66, 160, 66, 0.15);
        transition: background-color 200ms linear;
    }

    .fail.option.selected {
        background-color: rgb(212, 0, 0, 0.15);
        transition: background-color 200ms linear;

    }

    .option.selected {
        cursor: default;
        -webkit-box-shadow: inset 0px 0px 5px #33333352 !important;
        -moz-box-shadow: inset 0px 0px 5px #33333352 !important;
        box-shadow: inset 0px 0px 5px #33333352 !important;
        opacity: 1;
        /* color: rgba(255, 255, 255, 0.9); */
        /* border: 1px solid #555; */
    }
</style>

<script>
    $('.confirm-status-modal').hide()

    $('.second-check-save').click(function () {
        $('#qc_status_second_check_input').val($(this).attr('data-value'))

        header = $(this).text() + ' ' + $('.option').attr('data-value') + ' classification of ' + $('.confirm-status-modal .header').attr('data-worksheet')
        body_text = 'Are you sure you want to ' + $(this).attr('data-value') + ' the ' + $('.option').attr('data-value') + ' classification of this run?'
        $('.confirm-status-modal .header').text(header)
        $('.confirm-status-modal .body-text').text(body_text)

        $('.set-status-modal').fadeOut(function () {
            $('.confirm-status-modal').fadeIn();
        })
    })

    $('.cancel-submit').click(function () {
        $('.confirm-status-modal').fadeOut(function () {
            $('.set-status-modal').fadeIn();
        })
    })
</script>