VariantViewer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import include
from django.urls import path

from accounts import views


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('logout', views.LogoutSuccessfulView.as_view(),
         name='logout_successful'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('validate/<str:validate_hash>', views.ValidateAccountView.as_view()),
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('password', views.PasswordUpdate.as_view(),
         name='change_password'),

]

web/urls.py
from django.urls import include
from django.urls import path

from . import views

urlpatterns = [
    path('api/', include('web.routing')),

    path('', views.RedirectView.as_view(), kwargs={
         'update': False}, name='redirect'),
    path('section-update', views.RedirectView.as_view(),
         kwargs={'update': True}, name='change_section'),

    path('<slug:section>', views.HomeView.as_view(), name='home'),

    path('<slug:section>/search', views.SearchView.as_view(), name='search'),

    path('results/<pipeline_version>/<worksheet>/<sample>',
         views.SampleDetailsView.as_view(), name='sample_details'),


    ######################
    ##### AJAX VIEWS #####
    ######################

    path('ajax/run_first_check/<int:pk>',
         views.run_first_check, name='run_first_check'),

    path('ajax/run_second_check/<int:pk>',
         views.run_second_check, name='run_second_check'),

    path('ajax/modify_filters/<int:run>/<int:ss_sample>/<filter>',
         views.modify_filters, name='modify_filters'),

    path('ajax/update_selected_transcript/<int:run>/<int:ss_sample>/<int:transcript>',
         views.update_selected_transcript, name='update_selected_transcript'),

    path('ajax/load_variant_list/<int:run>/<int:ss_sample>',
         views.load_variant_list, name='load_variant_list'),

    path('ajax/refresh_classification_indicators/<int:run>', views.refresh_classification_indicators,
         name='refresh_classification_indicators'),

    path('ajax/load_variant_details/<int:run>/<int:stv>',
         views.load_variant_details, name='load_variant_details'),

    path('ajax/pin_variant/<int:run>/<int:stv>',
         views.pin_variant, name='pin_variant'),

    path('ajax/comment_update_or_create/<int:run>/<int:stv>',
         views.comment_update_or_create, name='comment_update_or_create'),

    path('ajax/save_evidence/<int:stv>',
         views.save_evidence, name='save_evidence'),

    path('ajax/archive_evidence/<int:document>',
         views.archive_evidence, name='archive_evidence'),

    path('ajax/load_previous_evidence/<int:run>/<int:current_stv>/<int:previous_stv>',
         views.load_previous_evidence, name='load_previous_evidence'),

    path('ajax/report_update_or_create/<int:run>/<int:ss_sample>/<report>',
         views.report_update_or_create, name='report_update_or_create'),

    path('ajax/generate_report/', views.GenerateReport,
         name='generate_report'),

    path('ajax/generate_variant_diagram/', views.GenerateVariantDiagram,
         name='generate_variant_diagram'),

    # Temporary to explore jbrowse during development
    path('jbrowse-testing/', views.JbrowseTestingView.as_view(),
         name='jbrowse-testing')

]

accounts/models.py
import hashlib
from datetime import datetime
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _

from easyaudit.models import LoginEvent


class UserManager(BaseUserManager):
    """Model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    def get_by_natural_key(self, username):
        case_insensitive_username_field = '{}__iexact'.format(
            self.model.USERNAME_FIELD)
        return self.get(**{case_insensitive_username_field: username})


def get_validate_hash():
    datetime_str = str(datetime.now())
    m = hashlib.md5()
    m.update(datetime_str.encode())
    return m.hexdigest()


class User(AbstractUser):
    """Custom user model to allow extension with custom fields.
    This must be established in the first migration (0001_initial.py), if not
    then auth user model cannot be changed.
    """

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    filters = models.ManyToManyField(
        'web.Filter',
        through="UserFilter"
    )

    default_section = models.ForeignKey(
        'db.Section',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='users'
    )

    validate_hash = models.CharField(
        max_length=255,
        default=get_validate_hash
    )

    objects = UserManager()

    @property
    def last_logged_in(self):
        try:
            return LoginEvent.objects.filter(user=self, login_type=0)[1].datetime
        except:
            return None

    @property
    def avatar_url(self):
        if self.is_superuser:
            return "https://avatars.dicebear.com/api/initials/" \
                   "su.svg?b=%23000000&bold=1"
        else:
            return f"https://avatars.dicebear.com/api/initials/" \
                   f"{self.first_name[0]}{self.last_name[0]}:.svg" \
                   f"?r=5&bold=1"


class UserFilter(models.Model):
    """
    Representation of filter associated with a particular VCF file.
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    filter = models.ForeignKey(
        'web.Filter',
        on_delete=models.CASCADE
    )
    selected = models.BooleanField(default=False)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from accounts.models import User
from db.models import Section


class CustomUserCreationForm(UserCreationForm):
    """Form containing all necessary modifiable user fields.
    """
    email = forms.EmailField(
        max_length=254,
        required=True
    )
    first_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'First Name'
            }
        )
    )
    last_name = forms.CharField(
        max_length=150,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Last Name'
            }
        )
    )

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
        )

    def clean(self):
        cleaned_data = super(CustomUserCreationForm, self).clean()
        email = cleaned_data.get('email')
        # Check that email is @nhs.net domain
        if email and "@nhs.net" not in email:
            self.add_error(
                'email', 'Must be an NHS.net address.')
        # Check that no accounts with this email address (irrespective of case)
        elif email and User.objects.filter(email__iexact=email).exists():
            self.add_error(
                'email', 'A user with that email address already exists.')
        return cleaned_data


class UpdateProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['default_section'].empty_label = 'Ask every time'

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'default_section')

accounts/views.py
from datetime import datetime
from hashlib import md5
import urllib

from accounts.forms import UpdateProfileForm
from django.contrib import messages
from django.views import View
from django.views.generic import TemplateView
from django.contrib.auth import login, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.db import transaction
from django.urls import reverse, reverse_lazy

from accounts.models import User
from accounts.forms import CustomUserCreationForm
from django.contrib.auth.forms import PasswordChangeForm
from db.tasks import send_email


def redirect_params(url, params=None):
    response = redirect(url)
    if params:
        query_string = urllib.parse.urlencode(params)
        response['Location'] += '?' + query_string
    return response


class LogoutSuccessfulView(TemplateView):
    """
    Template View to display logout successful page.
    """

    template_name = 'registration/logout_successful.html'


class RegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

    @transaction.atomic
    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.validate_hash = self.get_user_validate_hash(user)
            user.save()
            send_email.delay(
                email_type='validate_account',
                context={
                    'user': {
                        'model': ('accounts', 'User'),
                        'id': user.id
                    }
                },
                subject="Validate your VariantViewer account.",
                to=user.email
            )
            messages.info(
                request,
                "Thanks for registering. Please await an email to validate your"
                " account. If no email is received after 10 minutes, please"
                " first check your junk inbox before contacting Bioinformatics."
            )
            return redirect('login')
        else:
            return render(request, self.template_name, {'form': form})

    def get_user_validate_hash(self, user):
        m = md5()
        m.update(str(user.first_name + user.last_name +
                     str(datetime.now())).encode())
        return m.hexdigest()


class ValidateAccountView(UserPassesTestMixin, View):
    def test_func(self):
        user = self.user
        return not user.is_active

    def handle_no_permission(self):
        messages.error(
            self.request,
            "This validation link has expired as the associated user has already been activated."
        )
        return redirect('redirect')

    @transaction.atomic
    def get(self, request, *args, **kwargs):
        user = self.user
        user.is_active = True
        user.save()
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)
        messages.info(
            request,
            f"{user.first_name}, your account has been activated and you are now logged in."
            "Please select a relevent section of the laboratory."
        )
        return redirect('redirect')

    @property
    def user(self):
        validate_hash = self.kwargs.get('validate_hash')
        user = User.objects.get(validate_hash=validate_hash)
        return user


class ProfileDisplay(LoginRequiredMixin, DetailView):
    """User profile view
    """
    model = User
    context_object_name = 'account'
    template_name = 'profile.html'

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super(ProfileDisplay, self).get_context_data(**kwargs)
        account = self.get_object()

        context['form'] = UpdateProfileForm(instance=account)
        # context['history'] = get_user_audit_log(user=account)
        return context


class ProfileUpdate(LoginRequiredMixin, SingleObjectMixin, FormView):
    model = User
    context_object_name = 'account'
    form_class = UpdateProfileForm
    template_name = 'profile.html'

    def post(self, request, *args, **kwargs):

        params = {
            'next': self.request.GET.get('next')
        }

        self.object = self.get_object()
        form = UpdateProfileForm(request.POST, instance=self.object)
        print(form.errors)
        if form.is_valid():
            user = form.save()
            form.save()
            messages.success(request, "User profile successfully updated.")
            return redirect_params('profile', params)
        else:
            return render(request, self.template_name, {'form': form})

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)

    def get_success_url(self):
        return reverse('profile')

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdate, self).get_context_data(**kwargs)
        account = self.get_object()
        return context


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        view = ProfileDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = ProfileUpdate.as_view()
        return view(request, *args, **kwargs)


class PasswordUpdate(LoginRequiredMixin, DetailView):
    model = User
    context_object_name = 'user'
    template_name = 'registration/change_password.html'

    @transaction.atomic
    def post(self, request):

        params = {
            'next': self.request.GET.get('next')
        }

        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect_params('profile', params)
        else:
            return render(request, self.template_name, {'form': form})

    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super(PasswordUpdate, self).get_context_data(**kwargs)
        user = self.get_object()
        context['form'] = PasswordChangeForm(user)
        return context

accounts/templates/accounts-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#005eb8">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">


    <!-- Page Title -->
    <title>VariantViewer - {% block page_title %}{% endblock %}</title>

    <!-- Dependencies -->
    <link rel="stylesheet" type="text/css" href="{% static 'dependencies/fomantic/css/fomantic.min.css' %}">

    <script src="{% static 'dependencies/jquery/js/jquery.min.js' %}"></script>
    <script src="{% static 'dependencies/fomantic/js/fomantic.min.js' %}"></script>

    <!-- Project Files -->
    <link rel="stylesheet" href="{% static 'css/accounts-base.css' %}">
    {% block stylesheet %} {% endblock %}
</head>

<body>

    {% block content %} {% endblock %}

</body>

<script src="{% static 'js/base.js'%}"></script>

{% block javascript %} {% endblock %}

</html>

accounts/templates/profile.html
{% extends 'accounts-base.html' %}
{% load static %}
{% block page_title %}User profile{% endblock %}
{% block javascript %}
<script>
    $('.ui.dropdown')
        .dropdown()
        ;
</script>
{% endblock %}
{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column" style="max-width: 600px;">
        <div class=" ui top attached raised inverted segment logo-segment">
            <i class="huge dna icon" style="margin: 0;color:#005EB8"></i>

            <div class="text-title" style="margin: 0;margin-top: 5px;">
                <span style="font-weight: bold;font-size:x-large;">VARIANT</span>
                <span style="font-weight: lighter;font-size: x-large;color:#9aa4ac">VIEWER</span>
            </div>
        </div>

        <div class="ui raised inverted attached segment left aligned form-segment">

            {% if messages %}
            {% for message in messages %}
            <div class="ui {{message.tags}} message">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}

            <form class="ui large form" , method="post" , action="{% url 'profile' %}?next={{request.GET.next}}"
                novalidate>
                {% csrf_token %}

                {% if form.errors %}
                <div class="ui negative message" style="margin-top: 0;">
                    <div class="content">
                        {% for error in form.non_field_errors %}
                        <ul class="list">
                            <li>{{error|escape}}</li>
                        </ul>
                        {% endfor %}
                        {% for field in form %}
                        {% if field.errors %}
                        <ul class="list">
                            {% for error in field.errors %}
                            <li>{{field.label}}: {{error|escape}}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% endif %}

                <h4 class="ui dividing inverted header" style="margin-top: 0;">Personal Information</h4>

                <div class="field {% if form.first_name.errors %} error{% endif %}">
                    <div class="ui left icon input floating-label">
                        <i class="user icon"></i>
                        <input type="text" name="{{ form.first_name.html_name }}" placeholder="First name"
                            value="{{ form.first_name.value }}">
                        <label>First name</label>
                    </div>
                </div>

                <div class="field {% if form.last_name.errors %} error{% endif %}">
                    <div class="ui left icon input floating-label">
                        <i class="user icon"></i>
                        <input type="text" name="{{ form.last_name.html_name }}" placeholder="Last name"
                            value="{{ form.last_name.value }}">
                        <label>Last name</label>
                    </div>
                </div>

                <h4 class="ui dividing inverted header">Account Information</h4>
                <a href="{% url 'change_password' %}?next={{request.GET.next}}"
                    class="ui large left aligned labeled icon button">
                    <i class="key icon"></i>
                    Change Password
                </a>

                <h4 class="ui dividing inverted header">Default Section</h4>
                <div class="field {% if form.default_section.errors %} error{% endif %}">
                    <div class="ui fluid selection dropdown">
                        <input type="hidden" name="default_section" id="id_default_section"
                            value="{{form.default_section.value|default:""}}">
                        <i class="dropdown icon"></i>
                        <div class="default text">Select default_section</div>
                        <div class="menu">
                            {% for value, key in form.fields.default_section.choices %}
                            <div class="item" data-value="{{ value }}">
                                <div
                                    class="ui {% cycle 'blue' 'red' 'orange' 'yellow' 'olive' 'green' %} empty circular label">
                                </div>
                                {{ key }}
                            </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
                <input class="ui fluid large submit button" type="submit" value="Save Changes" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>

        <div class="ui bottom attached raised inverted segment footer-segment"
            style="display: flex;align-items: center;">


            <a href="{%if request.GET.next%}{{ request.GET.next }}{%else%}{% url 'redirect' %}{%endif%}"
                class="ui inverted tiny basic button">
                <i class="arrow circle left icon"></i>
                Back
            </a>

            <p style="margin-top: -2px;margin-left: auto;font-size: smaller;">User since
                {{account.date_joined|date:'d M Y'}}
            </p>


        </div>

    </div>
</div>

{% endblock %}

accounts/templates/section-select.html
{% extends 'accounts-base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock %}

{% block stylesheet %}
<style>
    .default-option.active {
        pointer-events: none;
        background-color: #bdbdbd73 !important
    }
</style>
{% endblock %}


{% block javascript %}
<script>
    $('.section-choice').click(function () {

        $('#section').val($(this).attr('data-section'))

        $("#section-select-form").submit();

    })

    $('.default-option').click(function () {

        $('.default-option').removeClass('active')
        $('.default-option i').removeClass('check')
        $(this).addClass('active')
        $('i', this).addClass('check')

        $('#default-choice').val($(this).attr('data-option'))
    })
</script>
{% endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid">
    <div class="column" style="max-width: 600px;">
        <div class="ui top attached raised inverted segment logo-segment">
            <i class="huge dna icon" style="margin: 0;color:#005EB8"></i>

            <div class="text-title" style="margin: 0;margin-top: 5px;">
                <span style="font-weight: bold;font-size:x-large;">VARIANT</span>
                <span style="font-weight: lighter;font-size: x-large;color:#9aa4ac">VIEWER</span>
            </div>

        </div>

        <div class="ui raised inverted attached segment form-segment">

            {% if messages %}
            {% for message in messages %}
            <div class="ui {{message.tags}} message">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}

            <div class="ui two inverted stretched raised link cards" style="max-height:4.5cm;height: 18vh;flex: 1;">
                <div class="ui card section-choice" data-section='cancer' style="background-color: #00A9CE;">
                    <div class="content"
                        style="display: flex;align-items: center;justify-content: center;flex-direction: column;">
                        <div class="center aligned header" style="color: rgba(255, 255, 255, 0.9);">Cancer</div>
                    </div>
                </div>

                <div class="ui card section-choice" data-section='rare-disease' style="background-color: #00A499;">
                    <div class="content"
                        style="display: flex;align-items: center;justify-content: center;flex-direction: column;">
                        <div class="center aligned header" style="color: rgba(255, 255, 255, 0.9);">Rare disease</div>
                    </div>
                </div>
            </div>

            <form id="section-select-form" action="" method="POST">
                {% csrf_token %}
                <input type="hidden" id="section" name="section" value="">
                <input type="hidden" id="default-choice" name="default-choice"
                    value="{% if user.default_section %}set-default{% else %}ask{%endif%}">
            </form>

        </div>

        <div class="ui bottom attached raised inverted segment footer-segment">

            {% if user.default_section %}

            <div style="margin-left: auto;" class="ui inverted tiny basic buttons">
                <div class="ui button default-option" data-option='ask'>
                    <span style="margin-right: 5px;">Ask every time</span>
                    <i style="margin: 0" class="circle outline icon"></i>
                </div>
                <div class="ui button default-option active" data-option='set-default'>
                    <span style="margin-right: 5px;">Update default</span>
                    <i style="margin: 0;" class="check circle outline icon"></i>
                </div>
            </div>

            {% else %}
            <div style="margin-left: auto;" class="ui inverted tiny basic buttons">
                <div class="ui button default-option active" data-option='ask'>
                    <span style="margin-right: 5px;">Ask every time</span>
                    <i style="margin: 0" class="check circle outline icon"></i>
                </div>
                <div class="ui button default-option" data-option='set-default'>
                    <span style="margin-right: 5px;">Set default</span>
                    <i style="margin: 0;" class="circle outline icon"></i>
                </div>
            </div>

            {%endif%}

        </div>


    </div>
</div>

{% endblock %}